version: '3'

services:
  database:
    container_name: streaming
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - '5434:5432'
    volumes:
      - data:/var/lib/postgres

volumes:
  data:
